### ISSUE TITLE
Fatal error: NSViewRepresentables must be value types: PlayerContainerView

### ISSUE THREAD

**Issue by magdics** [bnidevs/Mirror#1]
Getting this error when compiling source and clicking on menubar icon:

Thread 1: Fatal error: NSViewRepresentables must be value types: PlayerContainerView

**Comment by Gerzer** [comment]
Changing `PlayerContainerView` to be a structure instead of a class should be sufficient to fix this issue.

**Comment by bnidevs** [comment]
Currently out with COVID, will try to get to this before the weekend!

**Comment by bnidevs** [comment]
feel free to comment if still broken

**Comment by magdics** [comment]
Complies fine now, thanks
